### ISSUE TITLE
Tensor Dimension Mismatch in `extract_SlowFast_feature_LSVQ.py`

### ISSUE THREAD

**Issue by bingo-G** [winwinwenwen77/ModularBVQA#1]
When running the `extract_SlowFast_feature_LSVQ.py` script, I encountered the following error:

File "lib/python3.10/site-packages/pytorchvideo/models/slowfast.py", line 727, in forward x_s_fuse = torch.cat([x_s, fuse], 1) RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 60 but got size 61 for tensor number 1 in the list.

The root cause of this error seems to be that one of the samples has one extra frame. For example:

For `yfcc-batch1/749`, the original dimensions are `[1, 3, 241, 224, 224]`. After applying `inputs = pack_pathway_output(ele, device)`, the dimensions change to:

- `input[0]`: `[1, 3, 60, 224, 224]`
- `input[1]`: `[1, 3, 241, 224, 224]`

Then, when `slow_feature, fast_feature = model(inputs)` is executed, the dimensions of `x_s` and `fuse` become:

- `x_s`: `torch.Size([1, 64, 60, 56, 56])`
- `fuse`: `torch.Size([1, 16, 61, 56, 56])`

The mismatch between the time dimension `60` (for `x_s`) and `61` (for `fuse`) in dimension 1 causes the issue when trying to concatenate them, resulting in a failure.

Do you encounter a similar issue, and how can this be resolved?

**Comment by winwinwenwen77** [comment]
Hi Fengbin,

I did not encounter such a problem before. If you cannot solve it, I would suggest just skip the video.

Best,
Wen

发件人: Fengbin Guan ***@***.***>
日期: 星期三, 2024年12月25日 下午11:21
收件人: winwinwenwen77/ModularBVQA ***@***.***>
抄送: Subscribed ***@***.***>
主题: [Ext] [winwinwenwen77/ModularBVQA] Tensor Dimension Mismatch in `extract_SlowFast_feature_LSVQ.py` (Issue #1)
CAUTION: External email. Do not reply, click on links or open attachments unless you recognize the sender and know the content is safe.





When running the extract_SlowFast_feature_LSVQ.py script, I encountered the following error:

File "/envs/IQAmamba/lib/python3.10/site-packages/pytorchvideo/models/slowfast.py", line 727, in forward x_s_fuse = torch.cat([x_s, fuse], 1) RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 60 but got size 61 for tensor number 1 in the list.

The root cause of this error seems to be that one of the samples has one extra frame. For example:

For yfcc-batch1/749, the original dimensions are [1, 3, 241, 224, 224]. After applying inputs = pack_pathway_output(ele, device), the dimensions change to:

  *   input[0]: [1, 3, 60, 224, 224]
  *   input[1]: [1, 3, 241, 224, 224]

Then, when slow_feature, fast_feature = model(inputs) is executed, the dimensions of x_s and fuse become:

  *   x_s: torch.Size([1, 64, 60, 56, 56])
  *   fuse: torch.Size([1, 16, 61, 56, 56])

The mismatch between the time dimension 60 (for x_s) and 61 (for fuse) in dimension 1 causes the issue when trying to concatenate them, resulting in a failure.

Do you encounter a similar issue, and how can this be resolved?

―

**Comment by bingo-G** [comment]
Thank you for your response.

Since videos like this are not rare, skipping them entirely could potentially impact performance. Could you please help me check the dimensions of the video extracted from your sample `yfcc-batch1/749`? Specifically, I would like to know if the dimensions are `[1, 3, 241, 224, 224]` or `[1, 3, 240, 224, 224]`.

Thank you very much for your help!

**Comment by winwinwenwen77** [comment]
Hi,

I think the dimensions you asked for are [B, C, N, H, W]. B is the number of the video, C is the channel, N is the number of frames, H is the height, and W is the width. If this is the case, [1,3,240,224,224] should be correct as the video is 30 fps with an 8-second duration. However, I don’t think such a problem would affect the codes, and everything should go on smoothly.

Besides, I have attached feature dimensions for your reference.

***@***.***


***@***.***
发件人: BingoG ***@***.***>
日期: 星期五, 2024年12月27日 上午1:07
收件人: winwinwenwen77/ModularBVQA ***@***.***>
抄送: WEN Wen ***@***.***>, Comment ***@***.***>
主题: [Ext] Re: [winwinwenwen77/ModularBVQA] Tensor Dimension Mismatch in `extract_SlowFast_feature_LSVQ.py` (Issue #1)
CAUTION: External email. Do not reply, click on links or open attachments unless you recognize the sender and know the content is safe.


Thank you for your response.

Since videos like this are not rare, skipping them entirely could potentially impact performance. Could you please help me check the dimensions of the video extracted from your sample yfcc-batch1/749? Specifically, I would like to know if the dimensions are [1, 3, 241, 224, 224] or [1, 3, 240, 224, 224].

Thank you very much for your help!

―

**Comment by bingo-G** [comment]
Thank you for your detailed response!

I find it quite strange that even with the simplest code to read the video, my output is:
Total number of frames: 241
Frame rate (FPS): 29.97
Total duration: 8.04 seconds

Similarly, when I use the code from `ModularBVQA/extract_motion/motion_data_loader.py`, it also detects 241 frames. This is the source of my issue—if it had detected 240 frames, there wouldn’t have been an error.

I’m curious to know how you managed to read 240 frames. Did you do any additional processing on the data, or is there something wrong with the way I’m reading the video? Or perhaps my OpenCV version is incorrect?

Below is the code I used to read the video（Just for demonstration purposes, the actual processing still uses the ModularVQA code）:

```python
import cv2

# Load the video file
video_path = "/LSVQ/yfcc-batch1/749.mp4"  # Replace with your video file path
video = cv2.VideoCapture(video_path)

# Check if the video file was successfully opened
if not video.isOpened():
    print("Unable to open video file")
else:
    # Get the total number of frames in the video
    frame_count = int(video.get(cv2.CAP_PROP_FRAME_COUNT))

    # Get the frame rate (FPS) of the video
    fps = video.get(cv2.CAP_PROP_FPS)

    # Calculate the total duration of the video (in seconds)
    duration = frame_count / fps if fps > 0 else 0

    print(f"Total number of frames: {frame_count}")
    print(f"Frame rate (FPS): {fps:.2f}")
    print(f"Total duration: {duration:.2f} seconds")

# Release video resources
video.release()

**Comment by winwinwenwen77** [comment]
Hi,

It happens when the frame rate is not an integer. However, I have made the necessary round-off in the data loader.  As shown below:
***@***.***


***@***.***

发件人: BingoG ***@***.***>
日期: 星期日, 2024年12月29日 上午6:52
收件人: winwinwenwen77/ModularBVQA ***@***.***>
抄送: WEN Wen ***@***.***>, Comment ***@***.***>
主题: [Ext] Re: [winwinwenwen77/ModularBVQA] Tensor Dimension Mismatch in `extract_SlowFast_feature_LSVQ.py` (Issue #1)
CAUTION: External email. Do not reply, click on links or open attachments unless you recognize the sender and know the content is safe.


Thank you for your detailed response!

I find it quite strange that even with the simplest code to read the video, my output is:
Total number of frames: 241
Frame rate (FPS): 29.97
Total duration: 8.04 seconds

Similarly, when I use the code from ModularBVQA/extract_motion/motion_data_loader.py, it also detects 241 frames. This is the source of my issue―if it had detected 240 frames, there wouldn’t have been an error.

I’m curious to know how you managed to read 240 frames. Did you do any additional processing on the data, or is there something wrong with the way I’m reading the video? Or perhaps my OpenCV version is incorrect?

Below is the code I used to read the video（Just for demonstration purposes, the actual processing still uses the ModularVQA code）:

import cv2



# Load the video file

video_path = "/LSVQ/yfcc-batch1/749.mp4"  # Replace with your video file path

video = cv2.VideoCapture(video_path)



# Check if the video file was successfully opened

if not video.isOpened():

    print("Unable to open video file")

else:

    # Get the total number of frames in the video

    frame_count = int(video.get(cv2.CAP_PROP_FRAME_COUNT))



    # Get the frame rate (FPS) of the video

    fps = video.get(cv2.CAP_PROP_FPS)



    # Calculate the total duration of the video (in seconds)

    duration = frame_count / fps if fps > 0 else 0



    print(f"Total number of frames: {frame_count}")

    print(f"Frame rate (FPS): {fps:.2f}")

    print(f"Total duration: {duration:.2f} seconds")



# Release video resources

video.release()

―

**Comment by bingo-G** [comment]
Unfortunately, I cannot view the presentation or attachments you provided. Could you please check this again？

However, from my understanding, the number of frames read and the frame rate seem to be unrelated, as the frame length is read first and then the frame rate. It appears that when reading the frame length, the frame rate is not used as a parameter, as shown in the video_length in the image below. So whether the frame rate is an integer does not seem to affect the result of the frame length.
If my understanding is incorrect, please let me know.

![image](https://github.com/user-attachments/assets/f5b3d721-0020-4e89-b243-af4cedb1e28a)

**Comment by winwinwenwen77** [comment]
Hi,

I'm sorry to know that you cannot see my attachments, as I replied to the email directly.

The fact is that the round-off is reasonably necessary. You can see the last for loop in the data loader.  The integer is needed to cut the whole video into separate chunks. And SlowFast would extract features from the chunks.  I think the code should run smoothly without any changes.


<img width="957" alt="截屏2024-12-31 下午12 18 06" src="https://github.com/user-attachments/assets/90a01e3e-97a9-4722-b105-893e478f1a53" />

![WechatIMG895](https://github.com/user-attachments/assets/996dca79-1be3-41e8-ab22-86d0fac16e3f)
![WechatIMG896](https://github.com/user-attachments/assets/644e06cb-8bfc-4ad4-ae52-e3c1acce45d9)
![WechatIMG982](https://github.com/user-attachments/assets/01c22cdf-5b00-4934-a02b-0dc1e0df6bdb)

**Comment by bingo-G** [comment]
Sorry to bother you again. I believe I have an idea of what caused the error. It might be due to my modification of line 86 in `motion_data_loader.py`: `video_length_clip = self.num_frame`. This change likely led to the current issue.

However, I made this modification because I encountered the following bug before:

`File "ModularBVQA/extract_motion_original/motion_data_loader.py", line 86, in __getitem__
    video_length_clip = self.num_frame
AttributeError: 'VideoDataset_NR_LSVQ_SlowFast_feature' object has no attribute 'num_frame'`

To fix this, I fixed the bug in my own way, but this led to current problem. Now I believe this isn't a bug I can resolve on my own. The specific reason for the bug is that `self.num_frame` is not defined in the initialization of `VideoDataset_NR_LSVQ_SlowFast_feature`, yet it is used in later parts of the code. I find it hard to believe that this could run as expected.

Could you please help clarify this issue? I would really appreciate your assistance.

![image](https://github.com/user-attachments/assets/dfb555a5-62bf-4abc-9945-0315821aa5b8)
![image](https://github.com/user-attachments/assets/ce61f34b-19b6-4687-a1e0-253b3b00d379)

**Comment by winwinwenwen77** [comment]
Hi,

Sorry, there might be a bug in this version. Just set the video_length_clip=32 directly, as SlowFast extracts features in this way. I will update the GitHub later.
